service: api-tareas

provider:
  name: aws
  runtime: python3.12
  memorySize: 512
  timeout: 300
  region: us-east-1
  stage: ${param:stage}

  environment:
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    TABLE_TAREAS: ${env:TABLE_TAREAS}
    S3_BUCKET_TAREAS: ${env:S3_BUCKET_TAREAS}

  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole

  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
      - 'image/*'

functions:
  subirTarea:
    handler: subirTarea.subirTarea
    events:
      - http:
          path: tareas
          method: post
          cors: true
  
  listarTareas:
    handler: listarTareas.listarTareas
    events:
      - http:
          path: tareas
          method: get
          cors: true
  
  obtenerTarea:
    handler: obtenerTarea.obtenerTarea
    events:
      - http:
          path: tareas/{id}
          method: get
          cors: true
  
  actualizarTarea:
    handler: actualizarTarea.actualizarTarea
    events:
      - http:
          path: tareas
          method: put
          cors: true
  
  eliminarTarea:
    handler: eliminarTarea.eliminarTarea
    events:
      - http:
          path: tareas/{id}
          method: delete
          cors: true

package:
  patterns:
    - '!.venv/**'
    - '!node_modules/**'
    - '!.serverless/**'
    - '!__pycache__/**'
    - '!*.pyc'
    - '!.pytest_cache/**'
    - '!.git/**'
    - '!tests/**'

custom:
  pythonRequirements:
    dockerizePip: true
    dockerImage: public.ecr.aws/sam/build-python3.12:latest
    slim: true
    useDownloadCache: false
    useStaticCache: false
    invalidateCaches: true
    pipCmdExtraArgs:
      - '--no-cache-dir'